def judge(question: str, expects: str, answer: str, results: list) -> bool:
    """
    Decides whether the provided `answer` is correct based on the `expects` string.
    
    Arguments:
    - question: The original question string.
    - expects: The expected string/phrase you defined in questions.py
    - answer: The actual text generated by the pipeline.
    - results: The raw chunks retrieved (useful if you need to check citations).
    """
    # For a refusal (out of scope question), the pipeline usually returns a refusal string
    # like "I cannot answer this based on the documents."
    # So if we expected a refusal, we need to handle that!
    if "refuse" in expects.lower() or "cannot" in expects.lower():
        return "cannot answer" in answer.lower() or "not covered" in answer.lower()
        
    # Standard check: does the expected key phrase exist anywhere in the generated answer?
    # Converting both to lowercase makes our check case-insensitive.
    return expects.lower() in answer.lower()
